name: final_fantasy_guide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.13.0-228.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.3
  path: ^1.9.1
  marionette_flutter: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.4.2
  mockito: ^5.8.0
  build_runner: ^2.16.0
flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/data/trophies/
    - assets/data/journeys/
    - assets/covers/
    - assets/icons/final-fantasy-1-pixel-remaster/
    - assets/icons/final-fantasy-ii/
    - assets/icons/final-fantasy-iii/
    - assets/icons/final-fantasy-iv/
    - assets/icons/final-fantasy-v-v2/
    - assets/icons/final-fantasy-vi/
    - assets/icons/final-fantasy-vii/
    - assets/icons/final-fantasy-8-remastered/
    - assets/icons/final-fantasy-ix/
    - assets/icons/final-fantasy-x-hd/
    - assets/icons/final-fantasy-xii-the-zodiac-age/
    - assets/icons/final-fantasy-xiii/
    - assets/icons/final-fantasy-xiv-a-realm-reborn/
    - assets/icons/final-fantasy-xv-na/
    - assets/icons/final-fantasy-xvi/